services:
  spark-master:
    image: spark-horovod:latest  # Use your custom image
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
    ports:
      - "8090:8080"
    volumes:
      - ./training-cnn.py:/opt/spark/work-dir/training-cnn.py
    networks:
      - spark-network

  spark-worker-1:
    image: spark-horovod:latest  # Use your custom image
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - spark-network

  spark-worker-2:
    image: spark-horovod:latest  # Use your custom image
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge